main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('about/', views.About.as_view(), name="about"),
    path('index/', views.Index.as_view(), name="index"),
    path('index/new/', views.Create.as_view(), name="create"),
    path('index/<int:pk>/', views.Detail.as_view(), name="detail"),
    path('index/<int:pk>/update', views.Update.as_view(), name="update"),
    path('index/<int:pk>/delete', views.Delete.as_view(), name="delete"),

    path('users/', views.users, name="users"),
    path('user/<username>/', views.profile, name="profile"),

    path('moves/', views.moves_index, name="moves_index"),
    # path('moves/<int:move_id>/', views.move_show, name="move_show"),
    path('moves/new', views.Move_Create.as_view(), name="move_create"),
    path('moves/<int:pk>/update', views.Move_Update.as_view(), name="move_update"),
    path('moves/<int:pk>/delete', views.Move_Delete.as_view(), name="move_delete"),

    path('leagues/', views.leagues_index, name="leagues_index"),
    # path('leagues/<int:league_id>/', views.league_show, name="league_show"),
    path('leagues/new', views.League_Create.as_view(), name="league_create"),
    path('leagues/<int:pk>/update', views.League_Update.as_view(), name="league_update"),
    path('leagues/<int:pk>/delete', views.League_Delete.as_view(), name="league_delete"),

    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('signup/', views.signup_view, name="signup")
]

pokemon_collector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User

# Create your models here.

class League(models.Model):

    name = models.CharField(max_length = 20, blank = True)

    def __str__(self):
        return self.name

MOVETYPE_CHOICES = {
    ('Physical', 'Physical'),
    ('Special', 'Special'),
    ('Status', 'Status')
}

class Move(models.Model):

    name = models.CharField(max_length = 20)
    type = models.CharField(max_length = 20, choices = MOVETYPE_CHOICES)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['type']

TYPE_CHOICES = {
    ("Bug", "Bug"),
    ("Dark", "Dark"),
    ("Dragon", "Dragon"),
    ("Electric", "Electric"),
    ("Fairy", "Fairy"),
    ("Fighting", "Fighting"),
    ("Fire", "Fire"),
    ("Flying", "Flying"),
    ("Grass", "Grass"),
    ("Ground", "Ground"),
    ("Ice", "Ice"),
    ("Normal", "Normal"),
    ("Posion", "Poison"),
    ("Psychic", "Psychic"),
    ("Rock", "Rock"),
    ("Steel", "Steel"),
    ("Water", "Water"),
}

GENDER_CHOICES = {
    ("Male", "Male"),
    ("Female", "Female")
}

class Pokemon(models.Model):

    name = models.CharField(max_length = 20)
    img = models.CharField(max_length = 250)
    type = models.CharField(max_length = 20, choices = TYPE_CHOICES)
    description = models.TextField(blank = True)
    abilities = ArrayField(models.CharField(max_length = 20), blank = True)
    moves = models.ManyToManyField(Move, blank = True)
    gender = models.CharField(max_length = 10, choices = GENDER_CHOICES)
    evolved = models.BooleanField(default = False)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    leagues = models.ManyToManyField(League, blank = True)
    created_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']

main_app/views.py
from types import MethodDescriptorType
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from sre_constants import SUCCESS
from .models import Pokemon, Move, League
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

class Home(TemplateView):
    template_name='home.html'

class About(TemplateView):
    template_name='about.html'

class Index(TemplateView):
    template_name='index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name")
        if name != None:
            context['pokemons'] = Pokemon.objects.filter(name__icontains=name)
            context['header'] = f"Searching for {name.capitalize()}"
        else:
            context['pokemons']= Pokemon.objects.all()
            context['header']= "Index of Pokemon"
        return context

class Detail(DetailView, DeleteView):
    model = Pokemon
    fields = ['name', 'img', 'type', 'description', 'abilities', 'moves', 'gender', 'evolved', 'user', 'leagues']
    template_name = "detail.html"
    success_url = "/index/"

@method_decorator(login_required, name='dispatch')
class Delete(DeleteView):
    model = Pokemon
    template_name = "delete_confirmation.html"
    success_url = "/index/"

@method_decorator(login_required, name='dispatch')
class Create(CreateView):
    model = Pokemon
    fields = ['name', 'img', 'type', 'description','abilities', 'gender', 'evolved', 'user']
    template_name= "create.html"
    success_url ="/index/"

    def from_valid(self, form):
        self.object = form.save(commit = False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect('/index/')

@method_decorator(login_required, name='dispatch')
class Update(UpdateView):
    model = Pokemon
    fields = ['name', 'img', 'type', 'description', 'abilities',  'moves', 'gender', 'evolved', 'user', 'leagues']
    template_name = "update.html"
    def get_success_url(self):
        return reverse('detail', kwargs = {'pk': self.object.pk})

# User
@login_required
def profile(request, username):
    user = User.objects.get(username = username)
    pokemons = Pokemon.objects.filter(user = user)
    return render(request, 'profile.html', {'username': username.capitalize(), 'pokemons': pokemons})

@login_required
def users(request):
    users = User.objects.all()
    return render(request, 'users.html', {'users':users})


# PokemonMove

def moves_index(request):
    moves = Move.objects.all()
    return render(request, 'moves_index.html', {'moves': moves})

# def move_show(request, move_id):
#     move = Move.objects.get(id = move_id)
#     return render(request, 'move_show.html', {'move': move})

@method_decorator(login_required, name='dispatch')
class Move_Create(CreateView):
    model = Move
    fields = '__all__'
    template_name = 'move_create.html'
    success_url = "/moves/"

@method_decorator(login_required, name='dispatch')
class Move_Update(UpdateView):
    model = Move
    fields = ['name', 'type']
    template_name = 'move_update.html'
    success_url = "/moves/"

@method_decorator(login_required, name='dispatch')
class Move_Delete(DeleteView):
    model = Move
    template_name = 'move_delete_confirmation.html'
    success_url = "/moves/"

# League

def leagues_index(request):
    leagues = League.objects.all()
    return render(request, 'leagues_index.html', {'leagues': leagues})

# def league_show(request, league_id):
#     league = League.objects.get(id=league_id)
#     return render(request, 'league_show.html', {'league': league})

@method_decorator(login_required, name='dispatch')
class League_Create(CreateView):
    model = League
    fields = '__all__'
    template_name = 'league_create.html'
    success_url = "/leagues/"

@method_decorator(login_required, name='dispatch')
class League_Update(UpdateView):
    model = League
    fields = ['name']
    template_name = 'league_update.html'
    success_url = "/leagues/"

@method_decorator(login_required, name='dispatch')
class League_Delete(DeleteView):
    model = League
    template_name = 'league_delete_confirmation.html'
    success_url = "/leagues/"

# Login, Logout, Signup
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            u = form.cleaned_data['username']
            p = form.cleaned_data['password']
            user = authenticate(username = u, password = p)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/user/' + u)
                else:
                    print('The account has been disabled')
                    return HttpResponseRedirect('/login')
            else:
                print('The username/password is incorrect')
                return HttpResponseRedirect('/login')
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/index')
    
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            print('Hello', user.username)
            return HttpResponseRedirect('/user/'+ str(user))
        else:
            HttpResponse('<h1>Try again...</h1>')
    else:
        form = UserCreationForm()
        return render(request, 'signup.html', {'form': form})

main_app/templates/about.html
{% extends 'base.html' %}

{% block title %}
About Pokemon Collector 
{% endblock %}

{% block content %}
<main>
<h1>About Pokemon Collector</h1>
</main>
{% endblock %}

main_app/templates/battle_delete_confirmation.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Pokemon Battle</h1>

    <h4>Are you sure you want to delete <strong>{{battle.battle}}</strong>?</h4>
    
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes Delete">
        <a href="{% url 'battle_show' battle.id%}">Cancel</a>
    </form>

{% endblock %}

main_app/templates/delete_confirmation.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Pokemon </h1>
    <div class="delete-confirmation">
        <h4>Are you sure you want to delete <strong>{{pokemon.name}}</strong>?</h4>
    
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete Pokemon">
        <a href="{% url 'detail' pokemon.pk %}">Cancel</a>
    </form>
    </div>
    

{% endblock %}

main_app/templates/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Pokemon Details</h1>
    <div class="detail">
        <div class="detail-name-img">
            <h2>{{pokemon.name}}</h2>
            <img class="detail-img" src="{{pokemon.img}}" alt="{{pokemon.name}}">
        </div>
            
        <div class="detail-detail">
            <ul>
                <li>Type: {{pokemon.type}}</li>
                <li>Description: {{pokemon.description}}</li>
                <li>Abilities: 
                    {% for ability in pokemon.abilities %}
                        {{ability}}
                    {% endfor %}</li>
    
                <li>Evolved: {{pokemon.evolved}}</li>
                <li>Gender: {{pokemon.gender}}</li>
                <li>Moves: 
                    {% for move in pokemon.moves.all %}
                        {{move}}
                    {% endfor %}
                </li>
                <li>Leagues: 
                    {% for league in pokemon.leagues.all %}
                        {{league}}
                    {% endfor %}
                </li>
                <li>Date: {{pokemon.created_at}}</li>
            </ul>
        </div>
    </div>
     
    <div class="edit-delete">
        <a href="{% url 'update' pokemon.pk %}"> 
            <button>Update Pokemon</button>
        </a>
        <a href="{% url 'delete' pokemon.pk %}"> 
            <button>Delete Pokemon</button>
        </a>
    </div>
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block title %}
Pokemon Collector Home
{% endblock %}

{% block content %}
<p id="home-header">Pokemon Collector</p>
<p id="home-h3">Track and share your Pokemon collection!</p>
<p id="home-p">Add your pokemons and let them participate in leagues. Have fun with your pokemons and other trainers</p>
<div class="about"> </div>
{% endblock %}

main_app/templates/league_create.html
{% extends 'base.html' %}

{% block content %}
    <h1>Add a League</h1>
    <form class="create-form" action="" method="post">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="Submit">
    </form>

{% endblock %}

main_app/templates/league_update.html
{% extends 'base.html' %}

{% block content %}

<h1>League Update {{league.name}}</h1>
<form class="create-form" action="" method="post">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="Submit" />
</form>

{% endblock %}

main_app/templates/move_delete_confirmation.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Pokemon Move</h1>

    <div class="delete-confirmation">
        <h4>Are you sure you want to delete <strong>{{move.name}}</strong>?</h4>
    
        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Delete Pokemon Move">
            <a href="{% url 'moves_index' %}">Cancel</a>
        </form>
    </div>


{% endblock %}

main_app/templates/move_show.html
<!-- {% extends 'base.html' %}

{% block content %}
    <h1>Move Details</h1>

    <div>
        <div>
            <h2>{{move.name}} | {{move.type}}</h2>
            {% for pokemon in move.pokemon_set.all %}
                <p>{{pokemon.name}} {{pokemon.type}}</p>
            {% empty %}
                <p>No Pokemon has this move</p>
            {% endfor %}
        </div>
        <div>
            <a href="{% url 'move_update' move.id %}"><button>Update</button></a>
        </div>
        <div>
            <a href="{% url 'move_delete' move.id %}"><button>Delete</button></a>
        </div>
    </div>

{% endblock %} -->

main_app/templates/moves_index.html
{% extends 'base.html' %}

{% block content %}

<div class="page-h1">
    <h1 class="list-h1">Pokemon Moves</h1>
    <a href="/moves/new">+ Add a Pokemon Move</a>
</div>


{% for move in moves %}
    <div class="move-index">

        <div>
            <h3>{{move.name}} | {{move.type}}</h3>
        </div>
        <ul>
            {% for pokemon in move.pokemon_set.all %}
            <li>{{pokemon.name}}</li>
                {% empty %}
            <p>No Pokemon has this move</p>
            {% endfor %}
        </ul>

        <div class="league-edit-delete">
            <a href="{% url 'move_update' move.id %}">
                <button>Update</button>
            </a>
            <a href="{% url 'move_delete' move.id %}">
                <button>Delete</button>
            </a>
        </div>
    </div>
{% endfor %}
{% endblock %}

main_app/templates/profile.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{username}}'s Collection</h1>
    <h3>Collected Pokemons :  {{ pokemons|length }}</h3>
    
    <div class="index">
    {% for pokemon in pokemons %}
        <div class="collection-card-content">
            <a href="{% url 'detail' pokemon.pk %}">
                <div class="collection-name-img">
                    <h3>{{pokemon.name}}</h3>
                    <img src="{{pokemon.img}}" alt="{{pokemon.name}}">
                    <p>{{pokemon.type}} Type</p>
                </div>
            
                <div class="collection-detail">
                    <h3>{{pokemon.name}}</h3>
                    <ul>
                        <li><p>Type: {{pokemon.type}}</p></li>
                        <li>Description: <p>{{pokemon.description}}</p></li>
                        <li>Abilities: 
                        {% for ability in pokemon.abilities %}
                            {{ability}},
                        {% endfor %}</li>
                        <li>Moves: 
                            {% for move in pokemon.moves.all %}
                                {{move}}
                            {% endfor %}
                        </li>
                        <li>Evolved: {{pokemon.evolved}}</li>
                        <li>Gender: {{pokemon.gender}}</li>
                        <li>Leagues: 
                            {% for league in pokemon.leagues.all %}
                                {{league}}
                            {% endfor %}
                        </li>
                    </ul>
                </div>
            </a>
        </div>
        {% empty %}
        <p>No pokemons yet</p>

    {% endfor %}
</div>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}

{% block content %}

    <h1>Signup</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Sign up">
    </form>

{% endblock %}

main_app/templates/update.html
{% extends 'base.html' %}

{% block content %}
<h1>Update {{pokemon.name}}</h1>
<form class="create-form" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Update" />
</form>
{% endblock %}

main_app/templates/users.html
{% extends 'base.html' %}

{% block content %}
<h1>Trainers</h1>
    {% for user in users %}
    <div class="user-index">
        <a href="/user/{{user.username}}">
            <h2>{{user.username}} ({{user.pokemon_set.all|length}})</h2>
        </a>
        {% for pokemon in user.pokemon_set.all %}
            <p>{{pokemon.name}}</p>
        {% empty %}
            <p>No pokemon yet</p>
        {% endfor %}
    </div>
       
    {% endfor %}
{% endblock %}
                                                                                                                                                              